#include<stdio.h>
void hailstones(int n)
{ int i=0;
  while(n!=1)
  { printf("%-4d",n);
     i++;
     if(i%6==0) printf("\n");
     if(n%2==0) n=n/2;
     else       n=3*n+1;
  }
  printf("%-4d",n);
  i++;
  printf("\nNumber of hailstones generated:%d\n",i);	 
}

void main() 
{ int n;
  scanf("%d",&n);
  printf("Hailstones generated by %d:\n",n);
  hailstones(n);
}
